### ISSUE TITLE
Bug: game clock always shows "TODAY"

### ISSUE THREAD

**Issue by stvhwrd** [stvhwrd/Ticker#11]
Game clock shows only `TODAY` regardless of time left in period, etc.

This is definitely due to [`normalize_today()`](https://github.com/stvhwrd/Ticker/blob/master/ticker.py#L77-L84) method:

```python
    def normalize_today(self):
        date = get_date(0)
        if date.upper() in self.game_clock or \
            'TODAY' in self.game_clock or \
            'LIVE' in self.game_status or \
            'PROGRESS' in self.game_status:
            self.game_clock = 'TODAY'
        return
```

**Comment by scaryghosty** [comment]
fixed at https://github.com/scaryghosty/Ticker/commit/6b996c9f03890816128d0e725fc509838442ec75
