### ISSUE TITLE
Internet disconnected causes crash

### ISSUE THREAD

**Issue by stvhwrd** [stvhwrd/Ticker#2]
Script crashes when the internet is disconnected, even without live games in play. Scoreboard should remain static while without internet and continue to attempt refreshes at 30s intervals.

**Comment by stvhwrd** [comment]
Ticker produces a more user-friendly error text upon ConnectionError as of commit b219847ebafbb3d272ad07173d61f7353353aa42

**Comment by scaryghosty** [comment]
I think I fixed this issue as well... I'll be able to check better once I test on a day where there actually is a game! Check my fork above to see the fix in action.

**Comment by scaryghosty** [comment]
This issue was definitely fixed (at least under the scope of my testing) by the PR you merged from me... this issue can probably be closed. EDIT: https://github.com/stvhwrd/Ticker/pull/12
