### ISSUE TITLE
No clean exit

### ISSUE THREAD

**Issue by stvhwrd** [stvhwrd/Ticker#8]
There should be a "press Q to quit" or similar.  `Ctrl C` is a pretty ugly way to exit.

Good use case for threaded polling, perhaps..

**Comment by stvhwrd** [comment]
Ticker suppresses `Ctrl C` error message as of commit b219847ebafbb3d272ad07173d61f7353353aa42

**Comment by scaryghosty** [comment]
I have a working prototype for catching 'q':

```
Line 16: class ErrorQ(Exception):
Line 17:    pass

...

Line 126: Quit = input('\n\n')

...

Line 133: if Quit == 'q':
Line 134:    raise ErrorQ

...

Line 149: except ErrorQ:
```
Lines 150-153 would be the same as lines 137-140. You would also need to move the default except catcher to below this ErrorQ catcher.

Additionally, this only catches the 'q' on the next refresh. Not perfect but a start?

**Comment by stvhwrd** [comment]
Thanks @scaryghosty!  I really appreciate the contribution - I'll have a look this weekend and follow up here 🍻

**Comment by scaryghosty** [comment]
I should add that, if you haven't seen, I've forked your repo and you can test functionality by cloning my version. https://github.com/scaryghosty/Ticker

Also, this opens the door for even more commands to be issued as my version just captures any input and tests for 'q'. Unsure what those extra commands would be, but there is the possibility.

**Comment by stvhwrd** [comment]
Ideally, the program would quit within a second or two of user pressing `Q` - it's pretty dissatisfying to wait 10+ seconds for a small script like this to quit.   Are you interested in exploring threading at all?  I intended to try to have a separate thread (or something similar) monitoring the keyboard for user's keypress.

Some starting points:

* [17.1. `threading` — Thread-based parallelism](https://docs.python.org/3/library/threading.html)
* [How to use threads to get input from keyboard in python 3?](https://stackoverflow.com/questions/14043441/how-to-use-threads-to-get-input-from-keyboard-in-python-3)

**Comment by scaryghosty** [comment]
I've done threading in C before, so it'll be interesting to learn how another language handles it. Yes, I'd be up for it!

**Comment by scaryghosty** [comment]
Okay, so here's what I've got: https://github.com/scaryghosty/Ticker

There is one double-edged problem: this solution requires that you `sudo pip3 install keyboard` and that you run ticker.py as a super user. The problem IS avoidable and I can change it if you don't mind having to press `q` AND THEN `Enter`.

**Comment by scaryghosty** [comment]
ticker2.py stopped working so I removed it from my repo... this is probably beneficial because I assume you don't want to gate your program with super user status.

**Comment by scaryghosty** [comment]
UPDATE: changed my fork to just allow an `Enter` press. Any key can be pressed before `Enter` (EDIT: I've turned off echoing so none of them will appear on-screen) but if you press `Enter` at any time, the program closes gracefully.

**Comment by stvhwrd** [comment]
Thanks @scaryghosty!  What I had in mind here was a simple `Q` keypress (with nothing else required), similar to how one escapes from `top` or a `man page` in Linux.  I haven't looked at your implementation yet -- would this `Q` keypress behaviour be easily provided?

**Comment by scaryghosty** [comment]
Check this out: [http://www.jonwitts.co.uk/archives/896](http://www.jonwitts.co.uk/archives/896). I wrote a bit of test code and it works perfectly on Linux at least. I will change the `Enter` press to a `Q` press in my fork.

**Comment by scaryghosty** [comment]
https://github.com/scaryghosty/Ticker/commit/7d0a7865034e9d2781f3d06371e5b2282e9836ec
